"""Trace the michael.slop skull out of the mascot sprite into a Rust module.

Mirrors the classification `site/static/app.js:initSkullSpin` does at runtime:
crop the skull region of the 42x42 sprite, then label every pixel

    0 = air     (alpha < 40)
    1 = bone    (opaque, bright)
    2 = dark    (opaque, dim -- outline, eye sockets, nose, tooth gaps)

Storing the LABELS rather than pixels is what lets the effect light and spin the
skull: `2` must stay dark at every angle or the face stops reading, and that is
a property of the drawing, not of any one frame.
"""
import io
import os

from PIL import Image

SPRITE = os.path.join(os.path.expanduser("~"), "site", "static", "icons", "skeleton.png")
OUT = os.path.join(os.path.expanduser("~"), "panefx", "src", "skull_art.rs")

# The skull region, straight from app.js. Not re-derived: the site and panefx
# must show the same face, and eyeballing a second crop is how they drift.
# Height 19, not app.js's 21: the last two rows are the NECK stub below the
# teeth, and Michael wants the head alone -- a cleaner silhouette that also
# stops the jump lifting a floating neck around. The X region is unchanged, so
# the face still matches the site exactly.
# X starts one column further in and the width drops by three: one column of
# dark outline padding off the front, two off the back. Michael's ask, and
# measured safe before cutting -- the trace has 3 bone-free columns on the left
# and 2 on the right, so nothing of the drawing is lost.
#
# Column 23 of the OLD crop carries teeth, which is why the right trim is two
# and not three: one more would have cut into the jaw.
SX, SY, SW, SH = 9, 0, 23, 19

im = Image.open(SPRITE).convert("RGBA")
crop = im.crop((SX, SY, SX + SW, SY + SH))
px = crop.load()

# --- classify -------------------------------------------------------------
#
# TWO passes, and the second is the point.
#
# The sprite's own dark pixels are NOT used as the outline. They are baked into
# the art asymmetrically -- heavy under the bottom-right, thin across the front
# -- which reads as a lopsided smudge rather than a drawn edge once the skull
# starts turning. So they are discarded, and the outline is DERIVED from the
# bone shape instead: every empty cell touching bone becomes outline, at a
# depth measured in cells from the edge.
#
# Derived means uniform by construction. There is no way for one side to end up
# heavier than another, because the rule does not know which side it is on.
BONE = 1
AIR = 0

bone = [[False] * SW for _ in range(SH)]
for y in range(SH):
    for x in range(SW):
        r, g, b, a = px[x, y]
        # Opaque AND bright is bone. Everything else -- transparent, or the
        # sprite's own dark edge -- is treated as empty and re-outlined below.
        bone[y][x] = a >= 40 and (r + g + b) >= 384

def dist_to_bone(x, y, limit):
    """Chebyshev distance from (x, y) to the nearest bone cell, capped."""
    for d in range(1, limit + 1):
        for yy in range(y - d, y + d + 1):
            for xx in range(x - d, x + d + 1):
                # Only the ring at exactly distance d.
                if max(abs(yy - y), abs(xx - x)) != d:
                    continue
                if 0 <= yy < SH and 0 <= xx < SW and bone[yy][xx]:
                    return d
    return None

# The outline ramp, densest nearest the bone. Real ASCII rather than block
# shades: the skull itself is drawn in blocks, so an ASCII edge separates the
# silhouette from its surround instead of blending into it.
#
# Three cells deep -- one is a hard line, and beyond three the halo starts
# competing with the face for attention.
OUTLINE = "*+."
DEPTH = len(OUTLINE)

rows = []
counts = {"bone": 0, "outline": 0, "air": 0}
for y in range(SH):
    line = ""
    for x in range(SW):
        if bone[y][x]:
            line += "#"
            counts["bone"] += 1
            continue
        d = dist_to_bone(x, y, DEPTH)
        if d is None:
            line += " "
            counts["air"] += 1
        else:
            line += OUTLINE[d - 1]
            counts["outline"] += 1
    rows.append(line)

out = []
out.append("//! The michael.slop skull, traced out of the mascot sprite.")
out.append("//!")
out.append("//! GENERATED by `gen_skull.py` from")
out.append("//! `site/static/icons/skeleton.png`, region ({}, {}) {}x{}.".format(SX, SY, SW, SH))
out.append("//!")
out.append("//! The X region is app.js's, less one column of dark padding at the front")
out.append("//! and two at the back -- a tighter silhouette, with no bone lost (measured:")
out.append("//! the old trace had 3 bone-free columns left and 2 right). The")
out.append("//! HEIGHT is two rows shorter on purpose: app.js takes 21 rows, of which")
out.append("//! the last two are the neck stub below the teeth. Head alone is the")
out.append("//! cleaner silhouette, and it stops the jump lifting a floating neck.")
out.append("//!")
out.append("//! Cells are LABELS, not pixels:")
out.append("//!")
out.append("//!   ` ` air   `#` bone   `*` `+` `.` outline, densest nearest the bone")
out.append("//!")
out.append("//! The outline is DERIVED, not traced. The sprite\'s own dark pixels are")
out.append("//! baked in asymmetrically -- heavy under the bottom-right, thin across the")
out.append("//! front -- which reads as a lopsided smudge once the skull turns. They are")
out.append("//! discarded and the edge is regenerated from the bone shape, so it cannot")
out.append("//! be heavier on one side: the rule does not know which side it is on.")
out.append("//!")
out.append("//! Outline cells must stay DARK at every angle and light level, or the")
out.append("//! sockets fill in and the face stops reading as a face.")
out.append("")
out.append("pub const COLS: usize = {};".format(SW))
out.append("pub const ROWS: usize = {};".format(SH))
out.append("")
out.append("/// One row per line. See the module header for the alphabet.")
out.append("pub const SKULL: [&str; ROWS] = [")
for r in rows:
    out.append('    "{}",'.format(r))
out.append("];")

io.open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(out) + "\n")
print("{}: {}x{}  bone={} outline={} air={}".format(
    OUT, SW, SH, counts["bone"], counts["outline"], counts["air"]))
for r in rows:
    print("   |" + r + "|")
