"""Trace the michael.slop skull out of the mascot sprite into a Rust module.

Mirrors the classification `site/static/app.js:initSkullSpin` does at runtime:
crop the skull region of the 42x42 sprite, then label every pixel

    0 = air     (alpha < 40)
    1 = bone    (opaque, bright)
    2 = dark    (opaque, dim -- outline, eye sockets, nose, tooth gaps)

Storing the LABELS rather than pixels is what lets the effect light and spin the
skull: `2` must stay dark at every angle or the face stops reading, and that is
a property of the drawing, not of any one frame.
"""
import io
import os

from PIL import Image

SPRITE = os.path.join(os.path.expanduser("~"), "site", "static", "icons", "skeleton.png")
OUT = os.path.join(os.path.expanduser("~"), "panefx", "src", "skull_art.rs")

# The skull region, straight from app.js. Not re-derived: the site and panefx
# must show the same face, and eyeballing a second crop is how they drift.
# Height 19, not app.js's 21: the last two rows are the NECK stub below the
# teeth, and Michael wants the head alone -- a cleaner silhouette that also
# stops the jump lifting a floating neck around. The X region is unchanged, so
# the face still matches the site exactly.
# X starts one column further in and the width drops by three: one column of
# dark outline padding off the front, two off the back. Michael's ask, and
# measured safe before cutting -- the trace has 3 bone-free columns on the left
# and 2 on the right, so nothing of the drawing is lost.
#
# Column 23 of the OLD crop carries teeth, which is why the right trim is two
# and not three: one more would have cut into the jaw.
SX, SY, SW, SH = 9, 0, 23, 19

im = Image.open(SPRITE).convert("RGBA")
crop = im.crop((SX, SY, SX + SW, SY + SH))
px = crop.load()

rows = []
counts = {0: 0, 1: 0, 2: 0}
for y in range(SH):
    line = ""
    for x in range(SW):
        r, g, b, a = px[x, y]
        if a < 40:
            v = 0
        elif r + g + b < 384:
            v = 2
        else:
            v = 1
        counts[v] += 1
        line += " #."[v] if v != 1 else "#"
    # ' ' air, '#' bone, '.' dark
    rows.append("".join(" #."[v] for v in
                        [(0 if px[x, y][3] < 40 else
                          (2 if sum(px[x, y][:3]) < 384 else 1))
                         for x in range(SW)]))

out = []
out.append("//! The michael.slop skull, traced out of the mascot sprite.")
out.append("//!")
out.append("//! GENERATED by `gen_skull.py` from")
out.append("//! `site/static/icons/skeleton.png`, region ({}, {}) {}x{}.".format(SX, SY, SW, SH))
out.append("//!")
out.append("//! The X region is app.js's, less one column of dark padding at the front")
out.append("//! and two at the back -- a tighter silhouette, with no bone lost (measured:")
out.append("//! the old trace had 3 bone-free columns left and 2 right). The")
out.append("//! HEIGHT is two rows shorter on purpose: app.js takes 21 rows, of which")
out.append("//! the last two are the neck stub below the teeth. Head alone is the")
out.append("//! cleaner silhouette, and it stops the jump lifting a floating neck.")
out.append("//!")
out.append("//! Cells are LABELS, not pixels:")
out.append("//!")
out.append("//!   ` ` air   `#` bone   `.` dark (outline, eye sockets, nose, tooth gaps)")
out.append("//!")
out.append("//! The dark cells must stay dark at every angle and every light level, or")
out.append("//! the sockets fill in and the face stops reading as a face. That is a")
out.append("//! property of the drawing, which is why the labels are stored rather than")
out.append("//! a finished picture.")
out.append("")
out.append("pub const COLS: usize = {};".format(SW))
out.append("pub const ROWS: usize = {};".format(SH))
out.append("")
out.append("/// One row per line. See the module header for the alphabet.")
out.append("pub const SKULL: [&str; ROWS] = [")
for r in rows:
    out.append('    "{}",'.format(r))
out.append("];")

io.open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(out) + "\n")
print("{}: {}x{}  air={} bone={} dark={}".format(
    OUT, SW, SH, counts[0], counts[1], counts[2]))
for r in rows:
    print("   |" + r + "|")
