"""Draw the panefx tray icon and emit it as a Rust module.

A pixel "FX" over the teal desktop ground, in the michaelslop palette. Designed
AT 16x16 rather than drawn large and shrunk: a tray icon is 16px on most
machines, and anything downscaled to that size turns to mush. The larger sizes
in the .ico are the same art scaled by whole factors, which keeps every edge
hard.

Emitted as raw BGRA rather than a .ico file so `tray.rs` can hand it straight to
`CreateIconIndirect` -- no image crate, no file to ship alongside the exe, and
the "no new crates" rule holds.
"""
import io
import os

# michaelslop, from win98.rs
TEAL = (0x00, 0x80, 0x80)
BONE = (0xEC, 0xE9, 0xDD)
NAVY = (0x00, 0x00, 0x80)
AMBER = (0xFF, 0xCC, 0x00)
DARK = (0x0A, 0x0A, 0x0A)

# 16x16. `.` is transparent, `t` teal ground, `d` the dark edge, `F`/`X` bone,
# `a` amber accent.
#
# The letters are drawn as 5x7 pixel glyphs -- the smallest that keeps an F and
# an X legible with a gap between them.
ART = [
    "dddddddddddddddd",
    "dttttttttttttttd",
    "dtFFFFFtXttttXtd",
    "dtFttttttXttXttd",
    "dtFtttttttXXtttd",
    "dtFFFFttttXXtttd",
    "dtFttttttXttXttd",
    "dtFtttttXttttXtd",
    "dtFttttttttttttd",
    "dttttttttttttttd",
    "dtttttttfttttttd",
    "dtttttaffatttttd",
    "dtttttaaffaatttd",
    "dttttaaaffaaattd",
    "dttttttaattttttd",
    "dddddddddddddddd",
]

COLOURS = {
    "t": TEAL,
    "f": (0xFF, 0xEE, 0x88),
    "d": DARK,
    "F": BONE,
    "X": BONE,
    "a": AMBER,
}

W = H = 16


def bgra(scale=1):
    """Raw BGRA rows, top-down, at `scale` whole-pixel magnification."""
    out = bytearray()
    for y in range(H * scale):
        for x in range(W * scale):
            ch = ART[y // scale][x // scale]
            if ch == ".":
                out += bytes((0, 0, 0, 0))
                continue
            r, g, b = COLOURS[ch]
            # BGRA, premultiplied not needed for an opaque pixel.
            out += bytes((b, g, r, 255))
    return bytes(out)


rows = []
rows.append("//! The panefx icon, as raw BGRA pixels.")
rows.append("//!")
rows.append("//! GENERATED by `gen_icon.py`. A pixel \"FX\" over the teal michaelslop")
rows.append("//! ground, with the flame accent below it.")
rows.append("//!")
rows.append("//! Designed AT 16x16, not drawn large and shrunk -- a tray icon is 16px on")
rows.append("//! most machines and anything downscaled to that turns to mush. The larger")
rows.append("//! size is the same art at a whole-number scale, so every edge stays hard.")
rows.append("//!")
rows.append("//! Raw BGRA rather than a `.ico` so `tray.rs` can hand it straight to")
rows.append("//! `CreateIconIndirect`: no image crate, no file shipped beside the exe, and")
rows.append("//! the project's \"no new crates\" rule holds.")
rows.append("")

for scale, name in ((1, "ICON_16"), (2, "ICON_32")):
    px = bgra(scale)
    side = W * scale
    rows.append(f"/// {side}x{side}, BGRA, top-down.")
    rows.append(f"pub const {name}_SIZE: i32 = {side};")
    rows.append(f"pub const {name}: [u8; {len(px)}] = [")
    line = "    "
    for i, b in enumerate(px):
        line += f"{b},"
        if len(line) > 92:
            rows.append(line)
            line = "    "
    if line.strip():
        rows.append(line)
    rows.append("];")
    rows.append("")

io.open(os.path.join("src", "icon_art.rs"), "w", encoding="utf-8", newline="\n").write(
    "\n".join(rows) + "\n"
)
print("src/icon_art.rs written")

# A PNG preview, so the icon can be LOOKED at before it ships.
try:
    from PIL import Image

    for scale in (1, 8):
        im = Image.new("RGBA", (W * scale, H * scale))
        p = im.load()
        for y in range(H * scale):
            for x in range(W * scale):
                ch = ART[y // scale][x // scale]
                if ch == ".":
                    p[x, y] = (0, 0, 0, 0)
                else:
                    r, g, b = COLOURS[ch]
                    p[x, y] = (r, g, b, 255)
        im.save(f"icon-preview-{W * scale}.png")
    print("previews written")
except ImportError:
    print("no PIL; skipped previews")
