//! Xournal++ (stock). sl0p.ink -- Michael's build of it -- is NOT handled here:
//! its patch reads the house map (`housemap.rs`) and themes its own stylesheet
//! and settings colours, and doing both would apply the theme twice.
//!
//! Three files, all read when the app starts:
//!
//!   * `gtk-3.0\gtk.css` in GLib's config dir (`XDG_CONFIG_HOME`, else
//!     `%LOCALAPPDATA%`). A user stylesheet outranks the app's own, and GTK
//!     resolves a `@named` colour from the highest-priority provider that
//!     defines it -- so redefining the names sl0p.ink's `xournalpp.css` is built
//!     from (void, bone, spectral...) and GTK's `theme_*` names recolours the
//!     whole window without touching the install (for stock Xournal++, as far
//!     as its GTK theme draws from those names). Our lines sit between two
//!     marker comments; anything else in the file is the user's and stays.
//!   * `settings.xml` -- the canvas background, selection colours, dark/light
//!     variant, the default page colour and the pen palette. Xournal++ rewrites
//!     this file itself on exit ("Do not edit this file!"), so it is written
//!     ONLY while the app is closed. While it runs the change waits, and the
//!     daemon retries until it can.
//!   * a GIMP palette of the theme's colours, which `settings.xml` points the
//!     pen toolbar at.
//!
//! House puts back every settings value it changed and takes our block out of
//! gtk.css.

use super::{Outcome, Target};
use crate::palette::Rgb;
use crate::themes::catalog::Theme;
use crate::themes::derive::mix;
use crate::themes::fsutil::{write_atomic, Env};
use std::path::{Path, PathBuf};

pub struct Xournal;

/// (config folder name, process stem).
const APPS: &[(&str, &str)] = &[("xournalpp", "xournalpp")];

const BEGIN: &str = "/* >>> panefx theme -- written by panefx, removed on the house theme */";
const END: &str = "/* <<< panefx theme */";

/// settings.xml properties a theme sets.
const KEYS: &[&str] = &[
    "backgroundColor",
    "selectionBorderColor",
    "selectionMarkerColor",
    "activeSelectionColor",
    "themeVariant",
    "colorPalette",
    "pageTemplate",
];

fn argb(c: Rgb) -> String {
    (0xff00_0000u32 | (c.0 as u32) << 16 | (c.1 as u32) << 8 | c.2 as u32).to_string()
}

struct Pal {
    bg: Rgb,
    fg: Rgb,
    acc: Rgb,
    second: Rgb,
    light: bool,
}

fn pal(t: &Theme) -> Option<Pal> {
    let bg = t.rgb("background")?;
    let fg = t.rgb("foreground")?;
    let acc = t.rgb("accent")?;
    Some(Pal { bg, fg, acc, second: t.first(&["color5"]).unwrap_or(acc), light: t.is_light() })
}

/// The stylesheet block. The names are the ones sl0p.ink's `xournalpp.css` uses, and GTK's
/// own `theme_*`, so stock Xournal++ picks up what its theme exposes too.
pub fn css(t: &Theme) -> Option<String> {
    let p = pal(t)?;
    let c = |k: &str, d: Rgb| t.rgb(k).unwrap_or(d);
    let toward = |x: f64| mix(p.bg, p.fg, x);
    let edge = if p.light { Rgb(255, 255, 255) } else { Rgb(0, 0, 0) };
    let names: Vec<(&str, Rgb)> = vec![
        ("void", p.bg),
        ("crypt", toward(0.04)),
        ("crypt_hi", toward(0.08)),
        ("stone", toward(0.14)),
        ("stone_hi", toward(0.22)),
        ("bone", p.fg),
        ("bone_dim", mix(p.fg, p.bg, 0.4)),
        ("ash", c("color8", toward(0.5))),
        ("spectral", p.acc),
        ("viscera", c("color1", p.acc)),
        ("gold", c("color3", p.acc)),
        ("orchid", p.second),
        ("bevel_white", toward(0.22)),
        ("bevel_light", toward(0.14)),
        ("bevel_shadow", mix(p.bg, edge, 0.4)),
        ("bevel_dark", mix(p.bg, edge, 0.8)),
        ("theme_bg_color", p.bg),
        ("theme_fg_color", p.fg),
        ("theme_base_color", toward(0.04)),
        ("theme_text_color", p.fg),
        ("theme_selected_bg_color", p.acc),
        ("theme_selected_fg_color", p.bg),
        ("borders", toward(0.22)),
        ("unfocused_borders", toward(0.14)),
    ];
    let mut s = format!("{BEGIN}\n/* {} */\n", t.name);
    for (n, v) in names {
        s.push_str(&format!("@define-color {n} {};\n", v.to_hex()));
    }
    s.push_str(END);
    s.push('\n');
    Some(s)
}

/// `text` with our block replaced by `block` (or removed, for `None`).
pub fn splice_css(text: &str, block: Option<&str>) -> String {
    let mut out = match (text.find(BEGIN), text.find(END)) {
        (Some(b), Some(e)) if e > b => {
            let after = &text[e + END.len()..];
            format!("{}{}", &text[..b], after.strip_prefix('\n').unwrap_or(after))
        }
        _ => text.to_string(),
    };
    if let Some(block) = block {
        // Last, so it wins over any earlier definitions in the user's own file.
        if !out.is_empty() && !out.ends_with('\n') {
            out.push('\n');
        }
        out.push_str(block);
    }
    out
}

/// The raw `value="..."` of a settings.xml property, if present.
pub fn get_prop(xml: &str, key: &str) -> Option<String> {
    let needle = format!("<property name=\"{key}\" value=\"");
    let start = xml.find(&needle)? + needle.len();
    let end = xml[start..].find('"')?;
    Some(xml[start..start + end].to_string())
}

/// Set (or with `None`, remove) a property. `value` is raw XML attribute text.
pub fn set_prop(xml: &str, key: &str, value: Option<&str>) -> String {
    let needle = format!("<property name=\"{key}\" value=\"");
    if let Some(at) = xml.find(&needle) {
        let line_start = xml[..at].rfind('\n').map(|i| i + 1).unwrap_or(0);
        let vstart = at + needle.len();
        let Some(vend) = xml[vstart..].find('"').map(|i| vstart + i) else { return xml.to_string() };
        return match value {
            Some(v) => format!("{}{v}{}", &xml[..vstart], &xml[vend..]),
            None => {
                let line_end = xml[vend..].find('\n').map(|i| vend + i + 1).unwrap_or(xml.len());
                format!("{}{}", &xml[..line_start], &xml[line_end..])
            }
        };
    }
    match (value, xml.rfind("</settings>")) {
        (Some(v), Some(close)) => {
            format!("{}  <property name=\"{key}\" value=\"{v}\"/>\n{}", &xml[..close], &xml[close..])
        }
        _ => xml.to_string(),
    }
}

/// Swap the `backgroundColor=#......` inside a page template, keeping the rest.
fn template_with_bg(template: &str, bg: Rgb) -> String {
    match template.find("backgroundColor=#") {
        Some(i) => {
            let s = i + "backgroundColor=#".len();
            let e = (s + 6).min(template.len());
            format!("{}{}{}", &template[..s], &bg.to_hex()[1..], &template[e..])
        }
        None => template.to_string(),
    }
}

fn gpl(t: &Theme) -> String {
    let mut s = format!("GIMP Palette\nName: panefx {}\n# Written by panefx from the {} theme.\n", t.name, t.name);
    let named = [
        ("foreground", "Ink"),
        ("accent", "Accent"),
        ("color1", "Red"),
        ("color2", "Green"),
        ("color3", "Yellow"),
        ("color4", "Blue"),
        ("color5", "Magenta"),
        ("color6", "Cyan"),
        ("color8", "Grey"),
        ("color9", "Bright red"),
        ("color10", "Bright green"),
        ("color11", "Bright yellow"),
        ("color12", "Bright blue"),
        ("color13", "Bright magenta"),
        ("color14", "Bright cyan"),
        ("background", "Paper"),
    ];
    for (k, name) in named {
        if let Some(c) = t.rgb(k) {
            s.push_str(&format!("{:3} {:3} {:3} {name}\n", c.0, c.1, c.2));
        }
    }
    s
}

/// The settings values a theme wants, raw.
fn wanted(t: &Theme, current_template: Option<&str>, gpl_path: &Path) -> Option<Vec<(&'static str, String)>> {
    let p = pal(t)?;
    let mut v = vec![
        ("backgroundColor", argb(p.bg)),
        ("selectionBorderColor", argb(p.acc)),
        ("selectionMarkerColor", argb(p.acc)),
        ("activeSelectionColor", argb(p.second)),
        ("themeVariant", if p.light { "forceLight" } else { "forceDark" }.to_string()),
        ("colorPalette", gpl_path.to_string_lossy().into_owned()),
    ];
    if let Some(tpl) = current_template {
        v.push(("pageTemplate", template_with_bg(tpl, p.bg)));
    }
    Some(v)
}

struct Found {
    name: &'static str,
    stem: &'static str,
    settings: PathBuf,
}

fn installed(env: &Env) -> Vec<Found> {
    APPS.iter()
        .filter_map(|(name, stem)| {
            let settings = env.glib_config_dir().join(name).join("settings.xml");
            settings.exists().then_some(Found { name, stem, settings })
        })
        .collect()
}

fn gtk_css(env: &Env) -> PathBuf {
    env.glib_config_dir().join("gtk-3.0").join("gtk.css")
}

impl Xournal {
    fn write_css(&self, env: &Env, block: Option<&str>) -> Result<(), String> {
        let path = gtk_css(env);
        let before = std::fs::read_to_string(&path).unwrap_or_default();
        let after = splice_css(&before, block);
        if after.trim().is_empty() {
            if path.exists() {
                std::fs::remove_file(&path).map_err(|e| e.to_string())?;
            }
            return Ok(());
        }
        if after != before {
            write_atomic(&path, after.as_bytes()).map_err(|e| e.to_string())?;
        }
        Ok(())
    }

    /// Apply settings edits to every installed copy, skipping (and naming) any
    /// that is running.
    fn edit_settings(
        &self,
        env: &Env,
        edit: &dyn Fn(&str, &Found) -> String,
    ) -> (Vec<&'static str>, Vec<&'static str>, Vec<String>) {
        let (mut done, mut waiting, mut errors) = (Vec::new(), Vec::new(), Vec::new());
        for f in installed(env) {
            if env.is_running(f.stem) {
                waiting.push(f.name);
                continue;
            }
            match std::fs::read_to_string(&f.settings) {
                Ok(xml) => {
                    let next = edit(&xml, &f);
                    if next != xml {
                        if let Err(e) = write_atomic(&f.settings, next.as_bytes()) {
                            errors.push(format!("{}: {e}", f.name));
                            continue;
                        }
                    }
                    done.push(f.name);
                }
                Err(e) => errors.push(format!("{}: {e}", f.name)),
            }
        }
        (done, waiting, errors)
    }

    fn outcome(done: Vec<&str>, waiting: Vec<&str>, errors: Vec<String>) -> Outcome {
        if !errors.is_empty() {
            return Outcome::Failed(errors.join("; "));
        }
        if !waiting.is_empty() {
            return Outcome::Deferred(format!(
                "{} is open and would overwrite its settings; they are written when it closes",
                waiting.join(", ")
            ));
        }
        Outcome::NextStart(format!("{} recoloured; shows when it next opens", done.join(", ")))
    }
}

impl Target for Xournal {
    fn id(&self) -> &'static str {
        "xournal"
    }
    fn label(&self) -> &'static str {
        "Xournal++"
    }
    fn capture(&self, env: &Env) -> Option<serde_json::Value> {
        let mut apps = serde_json::Map::new();
        for f in installed(env) {
            let xml = std::fs::read_to_string(&f.settings).unwrap_or_default();
            let keys: serde_json::Map<String, serde_json::Value> = KEYS
                .iter()
                .map(|k| (k.to_string(), get_prop(&xml, k).map_or(serde_json::Value::Null, Into::into)))
                .collect();
            apps.insert(f.name.to_string(), keys.into());
        }
        (!apps.is_empty()).then(|| apps.into())
    }
    fn apply(&self, env: &Env, theme: &Theme) -> Outcome {
        if installed(env).is_empty() {
            return Outcome::Skipped("not installed".into());
        }
        let Some(block) = css(theme) else {
            return Outcome::Failed(format!("{} lacks a background, foreground or accent", theme.id));
        };
        if let Err(e) = self.write_css(env, Some(&block)) {
            return Outcome::Failed(format!("gtk.css: {e}"));
        }
        let gpl_path = env.panefx_dir().join("theme").join("xournal.gpl");
        if let Err(e) = write_atomic(&gpl_path, gpl(theme).as_bytes()) {
            return Outcome::Failed(format!("palette: {e}"));
        }
        let (d, w, e) = self.edit_settings(env, &|xml, _| {
            let mut out = xml.to_string();
            let tpl = get_prop(xml, "pageTemplate");
            for (k, v) in wanted(theme, tpl.as_deref(), &gpl_path).unwrap_or_default() {
                out = set_prop(&out, k, Some(&v));
            }
            out
        });
        Self::outcome(d, w, e)
    }
    fn restore(&self, env: &Env, saved: Option<&serde_json::Value>) -> Outcome {
        if installed(env).is_empty() {
            return Outcome::Skipped("not installed".into());
        }
        if let Err(e) = self.write_css(env, None) {
            return Outcome::Failed(format!("gtk.css: {e}"));
        }
        let (d, w, e) = self.edit_settings(env, &|xml, f| {
            let Some(keys) = saved.and_then(|s| s.get(f.name)) else { return xml.to_string() };
            let mut out = xml.to_string();
            for k in KEYS {
                out = set_prop(&out, k, keys.get(*k).and_then(|v| v.as_str()));
            }
            out
        });
        Self::outcome(d, w, e)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::themes::catalog::{load, Dirs};

    const XML: &str = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<settings>\n  <property name=\"themeVariant\" value=\"forceDark\"/>\n  <property name=\"backgroundColor\" value=\"4278519562\"/>\n  <property name=\"pageTemplate\" value=\"xoj/template&#10;backgroundType=lined&#10;backgroundColor=#05070a&#10;\"/>\n</settings>\n";

    fn theme(id: &str) -> Theme {
        load(&Dirs::bundled_only()).into_iter().find(|t| t.id == id).unwrap()
    }

    fn setup(name: &str) -> (PathBuf, Env, PathBuf) {
        let root = std::env::temp_dir().join(format!("panefx-test-xournal-{name}"));
        let _ = std::fs::remove_dir_all(&root);
        let env = Env::under(&root);
        let settings = env.glib_config_dir().join("xournalpp").join("settings.xml");
        std::fs::create_dir_all(settings.parent().unwrap()).unwrap();
        std::fs::write(&settings, XML).unwrap();
        (root, env, settings)
    }

    #[test]
    fn colours_are_decimal_argb_like_xournal_writes_them() {
        assert_eq!(argb(Rgb(0x05, 0x07, 0x0a)), "4278519562");
    }

    #[test]
    fn a_theme_then_house_gives_back_the_same_settings_and_css() {
        let (root, env, settings) = setup("roundtrip");
        let css_path = gtk_css(&env);
        std::fs::create_dir_all(css_path.parent().unwrap()).unwrap();
        std::fs::write(&css_path, "window { font-size: 12px; }\n").unwrap();
        let saved = Xournal.capture(&env);
        assert!(matches!(Xournal.apply(&env, &theme("catppuccin-latte")), Outcome::NextStart(_)));
        let xml = std::fs::read_to_string(&settings).unwrap();
        assert_eq!(get_prop(&xml, "themeVariant").unwrap(), "forceLight");
        assert_eq!(get_prop(&xml, "backgroundColor").unwrap(), argb(theme("catppuccin-latte").rgb("background").unwrap()));
        assert!(get_prop(&xml, "pageTemplate").unwrap().contains("backgroundColor=#eff1f5"), "new pages get the paper");
        let css = std::fs::read_to_string(&css_path).unwrap();
        assert!(css.starts_with("window { font-size: 12px; }\n"), "the user's own css stays");
        assert!(css.contains("@define-color spectral"));

        Xournal.restore(&env, saved.as_ref());
        assert_eq!(std::fs::read_to_string(&settings).unwrap(), XML, "settings back byte for byte");
        assert_eq!(std::fs::read_to_string(&css_path).unwrap(), "window { font-size: 12px; }\n");
        let _ = std::fs::remove_dir_all(root);
    }

    #[test]
    fn a_gtk_css_we_created_is_removed_on_house() {
        let (root, env, _) = setup("created");
        let saved = Xournal.capture(&env);
        Xournal.apply(&env, &theme("nord"));
        assert!(gtk_css(&env).exists());
        Xournal.restore(&env, saved.as_ref());
        assert!(!gtk_css(&env).exists());
        let _ = std::fs::remove_dir_all(root);
    }

    #[test]
    fn theme_to_theme_replaces_the_block_not_stacks_it() {
        let a = splice_css("", css(&theme("nord")).as_deref());
        let b = splice_css(&a, css(&theme("dracula")).as_deref());
        assert_eq!(b.matches(BEGIN).count(), 1);
        assert!(b.contains("Dracula"));
    }

    #[test]
    fn settings_xml_is_not_written_while_xournal_runs() {
        let (root, mut env, settings) = setup("running");
        env.fake_running = vec!["xournalpp".into()];
        assert!(matches!(Xournal.apply(&env, &theme("nord")), Outcome::Deferred(_)));
        assert_eq!(std::fs::read_to_string(&settings).unwrap(), XML, "untouched while it runs");
        assert!(gtk_css(&env).exists(), "the stylesheet is not the app's to overwrite, so it goes now");
        env.fake_running.clear();
        assert!(matches!(Xournal.apply(&env, &theme("nord")), Outcome::NextStart(_)), "the retry lands");
        let _ = std::fs::remove_dir_all(root);
    }

    #[test]
    fn not_installed_is_skipped() {
        let env = Env::under(&std::env::temp_dir().join("panefx-test-xournal-none"));
        assert!(matches!(Xournal.apply(&env, &theme("nord")), Outcome::Skipped(_)));
    }
}
