//! The `raalien_art` artwork, as shade levels.
//!
//! Traced from `ra-alien.ans` (ACiD-style CP437 block art):
//! a full-length Giger biomechanical xenomorph drawn in NEGATIVE
//! -- hatched half-block scanlines carve the creature out of the page rather
//! than fill it in -- from the ribbed elongated cranium and inner jaw down
//! through the segmented spine, clawed limbs and coiling tail.
//!
//! Near enough every glyph in the original is a shade block or a half block,
//! so the drawing reduces to a per-cell shade level. The original's own colour
//! is DISCARDED -- the effect supplies the colour instead.
//!
//! Storing shade levels rather than a finished picture is what lets the
//! animation light the scene: a cell's brightness is its shade times the light
//! reaching it, and the renderer picks the glyph from the result. The drawing
//! never changes -- only how it is lit.

pub const COLS: usize = 80;
pub const ROWS: usize = 508;

/// One row per line, one char per cell:
///   space = empty, `.:*#` = quarter/half/three-quarter/full shade,
///   `TBLR` = top/bottom/left/right half blocks.
///
/// ASCII stand-ins for the CP437 blocks so the source stays 7-bit and
/// nothing depends on this file's encoding surviving a checkout.
pub const ART: [&str; ROWS] = [
    "          TT##TBB                                         TB                    ",
    "         B                                                                      ",
    "              TT#T#BB                                       T#BB                ",
    "     BB##                                                                       ",
    "                T#B T#B                  BBBBBBTTTT T        T###BBBB           ",
    "BBB#B###L                                                                       ",
    "                  T#B T#BB       BBB#TTBBTTT                  T#BB   TTTBBTBBTTT",
    "TTTT#T#L                                                                        ",
    "                   R## #T######TTT#B#TT  BBTT                   TBT       #     ",
    "BBB####                                                                         ",
    "                  . ### ### #  BB#T    BT                      B  TBBB TTT#TTT  ",
    "  ####                                                                          ",
    "                     ###  #  B#TT     .  B                      BT   T#B  T     ",
    " ####                                                                           ",
    "                    .###  #B#T    BT   BT                       # TT #TTT B TT##",
    "#####                                                                           ",
    "                    *##L  #T   BTT  BBT                         L T##        .TT",
    "#####                                                                           ",
    "                    ### B#   BTT  B#T                          R#   ##    *    #",
    "#####                                                                           ",
    "                   ###B#T  BTT  BT .                          .L   *##    #    R",
    "###BT#                                                                          ",
    "                  B##TT   #T  B T  :                         :# T  ##   .   .  R",
    "## TB#                                                                          ",
    "                  ##T    #  B# *  TT                        * #T   ##  *    :   ",
    "#*   T#                                                                         ",
    "                 #TT    *  BT  # T                         #  B   ##  #      *  ",
    " B    ##                                                                        ",
    "                #TT  . :  T  :  B  .                      ## #    #  #       RL ",
    " ##  # T#                                                                       ",
    "               RTT   *   B#  *  TT :                     ## #  . #L #         #:",
    "  ##  # T#                                                                      ",
    "               #T  ..    #*  TTTBL *                    ##B#  . RL #           #",
    ": # #  # T#                                                                     ",
    "                  .     TT     BB  #                   ##B#  : RL T .           ",
    "#*  T   # T#                                                                    ",
    "               .  :   BBBB         #                  ##T#  *  ##BB:            ",
    " #  ##   # T#                                                                   ",
    "               :  *  BBBBB     TT  *                 #TT#. *  ##                ",
    "  #  T    # T#                                                                  ",
    "               *  #   TTT      BB  :               B#TT#*:*  ## TT:             ",
    "  ## ##    # ##                                                                 ",
    "               #  # TTTTTT     BB  .              #TB *#*#  ###BB               ",
    " B##*  B    # ##                                                                ",
    "               #     BBBBB     BB   .            #BT B###  ###   .              ",
    "B####*  B    ####                                                               ",
    "                #    BBBBB     BB . .          *# # TT##  ###     BBB#BBB#TTBBBB",
    "#T . *:  B    ####                                                              ",
    "                TT#     B      BB : :     .    #   # TT  ###  B##BBTTT         #",
    "  T   ..       ####                                                             ",
    "                  BTB T### B   B  * .     :    LL   TT# ##BBTT      B  B      : ",
    "        .  T     ###B                                                           ",
    "                   LRL R#L   B TT #..     *    RR      ##TT     BBTTTTTTT  TT T ",
    " T B     TTTTT B B TT#B                                                         ",
    "                    R   ##    TB###:.     #     LR   .R#BB BBBTT    BBBBTTTBBB  ",
    "     T       B  BBBB###TB                                                       ",
    "          TTBB      R   ##L    #T #*            R#L .*##T##T   BBTTT           B",
    "BB     TB        T###TBT                                                        ",
    "              #B    #B   ##  TT## B#      T      T#  .###T  BTT                 ",
    "  B       BT  B  B#TB#                                                          ",
    "               T B   ##   #L   BB  RL       #  TTBTBB  TBBBT                    ",
    "   T       #BT  T####                                                           ",
    "                 #T   #   R#L  BB#  #     #   #   ##TBTBBBBBB B   BBBBB         ",
    "    .       ###  R##*#                                                          ",
    "                  ##   #   ##L    #B T     #   *    BB TTTT            TTTBB    ",
    "     TB      ### R#::. B                                                        ",
    "                   ##   #   L#  #BT   B     TTB :     ##                 .:##B  ",
    "T     BTTB    #T  T:. BT                                                        ",
    "                    #B   *  T##     .  TBB      .       #                 ####B ",
    " *      T##B  ##  #:   T                                                        ",
    "                    ####  :  R##     .# B                *              BT## ##L",
    " T        ##:  *  #B   T                                                        ",
    "                   R##  #  .  T##B  BB# TTTBBBBB B                   BBTBT  ##T ",
    "          R#:  :  R#L   B                                                       ",
    "                   R##  #B     TBBTTT######BBBBBB             BBBBBB#TTTBBTTBT B",
    "  B        #:     R##   #B                                                      ",
    "                  B## BB##B#B     TTTTTBB BTTTBBBBBBB BB BB BBBB####T BT#BT     ",
    "TB TB      #   B   ###   #BB                                                    ",
    "                  ####   ## TBB                    TTTTT#TT#TT B TTT####T       ",
    " #  #      #       *R##B ###L                                                   ",
    "                 T##T TTTT    TBB     T  T  T  T  T  T  T  T    TBBBB LR      T ",
    " :  *      #   #   . #T#####L                                                   ",
    "               B##T   :  .      TBB   #  T  T  #  T  T  T  T   B      #L      : ",
    " .  . #   B     ##     TTT###B                                                  ",
    "             B##T  :  *  *  .     TTTT#BB             B  B *   TT      BT       ",
    " B       *      T  #      TTT#BB                                                ",
    "           B#TT  BBT  #  T  *  :B          TTTTTTTTTTTTTTTTTTTTB   BB *  BB  T B",
    "BBBBBTT  *     #     T       TTT #B                                             ",
    "       BBB#####BBBBTTT       TB  ##BBB##TTTTTTTTT TT T  T    T  B    * #   BBBB#",
    "#TT  BBBT     *                  TTTT                                           ",
    "                              BBBBTTTTT    TTTTT                 #:   TT##TTBB##",
    "##BB###T     :                                                                  ",
    "                             #TTTT     TTT                      #.     BB B###TT",
    "BB##T#T    .                                                                    ",
    "                           BTT   .# TT                         TBBBBBTBBB###TBT ",
    "B##T                                                                            ",
    "                          ##   *TTT                          BB#T#TT**####TBT B#",
    "#T                                                                              ",
    "                         ##T #BTT                          BB#T BT :**##TBT B##T",
    "                                                                                ",
    "                        ####T                            BB#T BT .. T#TBTB###T  ",
    "                       R##T                            BB#T BT  .  BTBTBBB#T    ",
    "                       R##                           BB#T BT  .  BTBTBTB#T      ",
    "                          R                                                     ",
    "                        LL                         BB#T BT B   BTBT TB#T      B ",
    "                          LL                                                    ",
    "                        #                        BB#T BT     BTBT  ###T         ",
    "  B                      R#L                                                    ",
    "                        R                      BB#T BT BT  BTBT  B##T  BBB      ",
    "    B                    L#L                                                    ",
    "                        R                    BB#T BT BT  BTBT  BTBT       TTBBB ",
    "     TB                 R#R                                                     ",
    "                                          BB###BBT BT  BTBT  BTBT              T",
    "#B  .  #                L#L                                                     ",
    "                                        B#B##T## B##B TBT  BTBT                 ",
    " TT  :  T              T#L                                                      ",
    "                                      B#######BTTBBBTBT  BTBT                   ",
    "  ##B *  #           BT #R                                                      ",
    "                                     TB#####TTTTTTTT   BTBT                     ",
    "   ## #  B         BT#B#                                                        ",
    "                                    # ##T TTTTTTTT    BBT  .                    ",
    "   ## B  #       BT#B## T                                                       ",
    "                                   # ###TTTTTTTTTTTT TBL:  ..  .                ",
    "  ##    #      BT#B### T                                                        ",
    "                                  ####     TTTTTTTT##T    .**  :  .  .          ",
    " #   ###     BT B #T# T                                                         ",
    "                                 B#####BBBBBBB          .:###  #  *  * .        ",
    "#B##TTT TBB#T##  # #T                                                           ",
    "                                ##..T##B  TT###  BBB  B  B  B  B          BBB TT",
    "T  BBBB#TT  T  BT ##                                                            ",
    "                               B#: #  ###  ####BB              #BBTBBBBBBBBBBTBB",
    "BBBTT BBB    B#T #B                                                             ",
    "                              #T#   #  TTTTT *  #TTTT        T T  # TTTTTTTTTTTT",
    "    TT   BBT##  B                                                               ",
    "                            BTT B   #.         ##B    TTTT BBBBBBBTBBBBBBBBBBBBB",
    "B**#T TTT   B#B                                                                 ",
    "                          BBT B###*    TTTBBBTT ####BBB           T         ....",
    ":::::.    BT#T                                                                  ",
    "                        BBTTBBTT    B##BBBBBBBBB#TTTTT#####BBB     T TTTTB      ",
    " ...   BBTBT                                                                    ",
    "                      BBTT                             TTTTTTT##########B #####B",
    "BBBBB#T##T                                                                      ",
    "                    BTT                                            TTTTTT  TT##T",
    "TTTTTT#T                                                                        ",
    "                                                                               T",
    "TTTTT                                                                           ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                         BB                     ",
    "                                                  B#  BLR#L*  *                 ",
    "                                              BBB R###TBT#B##B BT               ",
    "                                            R##T T###TB######TB##TBBT#          ",
    "                                            RT B##T#TR#####: R####BB            ",
    "                                          BRR B##*   RR###T  L###:   BT#.       ",
    "                                         RBT RL #   RR##:   R###:    L#:  .     ",
    "                                         RRL ###.   RR##    RR#*    R#R  B##    ",
    "                                        R L R#RL     ##L    RR#.    R##B####:   ",
    "                                      TLR L  ##L     L#L     R#    . L####T     ",
    "       BB#T#B                        LR## RL RLRL    ##      RL   .  L#####B  :B",
    "                                                                                ",
    "     BTT#####L                       # R#L #  T#L    LR#     #L      R######* .#",
    "B  .                                                                            ",
    "    BBT#*:.#RL                       LL #TB #B#LR#B# R#L    :#      .R##########",
    "##  *                    BBT##                                                  ",
    "     ...#*.##                        L#B T R## R#L#L L## *  :#     * #*#########",
    "###   B                BT# B*:                                                  ",
    "      .  #L#R                        #BTLRL #L R#L  B#####L*##B  B#.R*#########*",
    "*###B  *             BT##.*#                                                    ",
    "     .    #.#L                       #T     B  RBL ####T  BT######T #:#########*",
    ":**###               RL#.*##*                                                   ",
    "     :     #.#                        *BTB      #  T#T   B#BT ##T  B:###########",
    "#**####B              ##.####*                                                  ",
    "     *      #.B                        T#R      *  **   B##  T   BT.#####*######",
    "########B              L.*###*.                                                 ",
    "             #.B                        T##    .   :    ###B   BTB#######*######",
    "##########             R#*###*                                                  ",
    "      B       #.B                         T#        .  R# *#LBT#*########.*#####",
    "##*########B           R#**##                                                   ",
    "      TB       #.B                          T  B       #L # B#.*########*#**####",
    "###:**######B          R#**#*                                                   ",
    "                #.B                                    # RL## *#########*#B*####",
    "###*:**#######         R#*##*                                                   ",
    "                 #.B                                   R   # .*#########: #*####",
    "####***########        R#*##:                                                   ",
    "         T        #.B                                  RL R# .#########*###**###",
    "###############B       L#*##:                                                   ",
    "           B  B    TBTB                                R  ##.*#######*** ###**##",
    "################       L.*##.                                                   ",
    "             T#T     TBTB                             .   *#:######*****####**##",
    "################      R#*###  :                                                 ",
    "                B#     #.TB                            :   *#########**#####:###",
    "################*     L####: B                                                  ",
    "                  TBB    T#B                           *  .*##** *###*######B###",
    "######**########T    R#*##: BT                                                  ",
    "                    #B     TTBB                   #     # .*###  R##*:######T*##",
    "######*:*#######    B#*#*  BT                                                   ",
    "                       B  T##B#BB                RL       .*##   ###*########*##",
    "########*#######:  BB**                                                         ",
    "                             TTT#BBB              T   B    *###  R##*#######:###",
    "########*#######*B#**    B                                                      ",
    "                          *     TT##BBBB               B    ##*  R###:##.BB#####",
    "##################.     BT            BT               B                 TTBTT..",
    "#TBBB         TT   .**:  R####..##########*:#############*     B           BT#T#",
    "                                      TT*..B***#B      B .  .:   R#####.########",
    "B.   TTT:T#######:       R       BTBT                                           ",
    "                T#             BBTTTB         TTT      T    .:    ####*#########",
    "T         T######.              B#T   .                                         ",
    "                   B          #TTT#TT##T     T**BBBB    B .  .    #############T",
    "            *####             BT#T   *                                          ",
    "                    #        *       TTTTBB   BTTTT    TT .      R############. ",
    "             *###            ##T      .                                         ",
    "                      B      .            BTB           B  .     R##########TT  ",
    "             .###          BT#T                                                 ",
    "                       T      .    TB       B#B         T*       #########T     ",
    "              R##         T#TT                                                  ",
    "                                     TTB      T#    :           ****####:       ",
    "              R##        ###T   B                                               ",
    "                                        TB      *    .   R      :#**###T        ",
    "              R##        ##   #L                                                ",
    "#BB                              T BBT B  T       :            :*#:..##.        ",
    "               ##           BBBB                                                ",
    "**.#BB                            TT BT#T          .      . *  .*:.  RL         ",
    "               ## BBB##  BTT#..#TTB                                             ",
    "#TTTT.#BB                         L  #  B T                    .#.   .#         ",
    "               #*  .:T BTB#TTTTT#.*L                                            ",
    "#      TTTB                  BBBBB     BTT  B                T  *    .#.        ",
    "              ##     B#TT        **#                                            ",
    " TB        TB              BTTTTTT#B       T                  B  :   .##.       ",
    "              *    BTT      B B :##T                                            ",
    "      B      *            T  BBB    TB         *               B      :         ",
    "             :           *      TT                                              ",
    "                           BT #BTBB   T                    .    #     ..        ",
    "            .            BTTTB                                                  ",
    "                          T: T B TT T     *                 .    *              ",
    "                     BB#TTTT T.                                                 ",
    "                          TTTTT BBTT#B     TB       .      .*     T*            ",
    "                   T                                                            ",
    "                         * B  BT#.B#B##      TB       :  ..*L       T           ",
    "                *                                                               ",
    "                          B BT#.:####  T      T#        *##T      T#  TB        ",
    "       *     *                                                                  ",
    "                        B   L#.:*#TB            #TTB             R# #TB  *      ",
    "                    BBT                                                         ",
    "                       RL  R#*T*#T  *            ##TT:B    BB   .R:LB.L#BB  T   ",
    "T                  T    .:*B                                                    ",
    "                       #   #R R#L                 :   T*  *T   : R.R..LLBL#B BB ",
    "  B B         BT    B#BB   **B                                                  ",
    "                           RL  #                  R*B   T   # .*   #.# #.LLB.RLB",
    " R R.              TB*.#BB  **.                                                 ",
    "                       B   #    T       B          ##         .    R.LR.: R.: B:",
    " #L.:               TT#*:#L*  *                                                 ",
    "                       #B            B             T           L    T   T T#T TT",
    "   RL                 .#*#  B  #                                                ",
    "                       RL           T             #B              B             ",
    "                       .#       :                                               ",
    "                        L                          ##          R R.L            ",
    "  .                    *     *  .                                               ",
    " T                                                  T#B     B     T L           ",
    " B            .       .                                                         ",
    "                                                :     TTT  TTB  : .R:L          ",
    "R:            :                                                                 ",
    "                                      B          TB               TR.LRL B  B B ",
    "B              *                                                                ",
    "                         R           #T            TTBB         *   T .LR: RLR:R",
    ".L             *                                                                ",
    "                         L.          BB                  T        B    T T #T T ",
    "T   T         #                       *                                         ",
    " T                       *           T*T          TB           B   T#   BBB BBBT",
    "#        BBTT*                                                                  ",
    "                        R*     . .   BB                                    ##B  ",
    "      BTT   *                                                                   ",
    "                        R.L    ::    TTT                                    #T  ",
    "     T  BB  .                                                                   ",
    " #                       *      *    BB                                     #T  ",
    "   *    *# .                          #                                         ",
    "                                :    T*T                                    #   ",
    "        .# .                          #                                         ",
    " #                        :    .     B                                      R   ",
    "         #.                                                                     ",
    " #                         . .       T:                                     R   ",
    "     T  ..                                                                      ",
    "                                     .                                      R   ",
    "  BB   .:  *                          #                                         ",
    "BBB                        .         .T                                     R   ",
    "    T  #.#T                           #                                         ",
    " B                        *.         .                                      R   ",
    "TTB   ..                           BB##                                         ",
    "TTT                       :          B                                      RL  ",
    "   T ..                                                                         ",
    "BBB                       .         ..                                      RL  ",
    "TB  ..                             TTT                                          ",
    "BBB                                                                        R#L  ",
    "   ..                              BBB                                          ",
    "BBB                             .   *                                      R##L ",
    "B .:                               BBB                                          ",
    "BBB                             :                                        T#R##L ",
    " .*                                BBB                                          ",
    "BBB                              *                                          ##L ",
    ".*                                 BBB                                          ",
    " B                               *                                     T  T  # .",
    "#                                  BBB                                          ",
    " *                                #                                     BT   TB#",
    "                                   BBB                                          ",
    " .                                 #                             .     B T#  ## ",
    "                                    BB                                          ",
    "                              :     T#BBT                       .       TB# #T  ",
    "                                    BB                                          ",
    "BB #                         .        T                        :          ##    ",
    "                                     B                                          ",
    "BB *                         *  T         :                    *        BT      ",
    "   .                          B*    TT                                          ",
    "BB :                         L   B       #                    RL      *         ",
    " B*                          RL   #  #                                          ",
    "BB .                         L  #T  *   T    B                 TBBTT          BB",
    "##                           L#  #* ##                                          ",
    "BB                          R    BB  #T  .    #B                               *",
    "#                            R #B :                                             ",
    "B  .                        R    #:L :   RL   B                     BBBB      :#",
    "                              #BT . BB                                          ",
    "TT :                        L         .   *B    #B            BBBTT:..**T    BT ",
    "                               T#                                               ",
    "#  *   *                    L     #*L     #*     TT       B TT      .*#T        ",
    "                                  . TT                                          ",
    "####   #                    #L    TT      ###B  TTB               .:*T          ",
    "                                  : BB                                          ",
    " B  *                       RL     B*B   #  #TB   #*             ..T            ",
    "                                  *  #                                          ",
    " TT #.                       L      #TT      #*     .           *               ",
    "                                  ####                                          ",
    "BBBB#                         L      BB#  B  ###                                ",
    "                                   BBB                                          ",
    "BB                            L     T#*.#  #TTTT#                               ",
    "                                 B#BBB                                          ",
    "BB .                          L     TTT     #  ###                              ",
    "                                #TBBBB                                          ",
    "BB :##B                       R       BB#*   #  #B#                             ",
    "                               R #TBBB                                          ",
    "B  *   T                      R       *#*#B   #   #                             ",
    "                               L#  BBB                                          ",
    "TT #.   *                     R         T  B   *   *                            ",
    "                               RL  BB                                           ",
    " .:#:                          L        BB##B  *   *                            ",
    "                                T* T#T                                          ",
    "       *B                              *#*:##   :   :                           ",
    "                                     .                                          ",
    " BB #   RL                              TT      .   :                           ",
    " BB *#  #R                               BB*#B       .                          ",
    "                                     T                                          ",
    " BB : B# L                               *#:#T   :   .                          ",
    "                                     #                                          ",
    " BB . TB#                          B             R                              ",
    "                                   ###                                          ",
    " BB   #T                                   B: *   #                             ",
    "                                   BBB                                          ",
    " B  .                                      T#T   R #                            ",
    "                                   BBB                                          ",
    " TT :                                         B  R   .                          ",
    "                                   BBB                                          ",
    " #  *                                .      B#   #   *:                         ",
    "                                     #                                          ",
    " ####                                .       T   # #  #                         ",
    "                                      :      B  RL .: T#                        ",
    "                              RL    B                                           ",
    "BBBBBBBBB                             :     T#  L  :*#B                         ",
    "                              L#     T                                          ",
    "      ###                              *       RL   #.#B                        ",
    "                              R #B  #                                           ",
    "TTT     B                               *      L     TT T                       ",
    "                               #BT  *#                                          ",
    "BBB     #                                #   BT   BB.*T#.#                      ",
    "                                T#  :#                                          ",
    "BBB     *                                  T    BT T#..:##BBB                   ",
    "                                    .#                                          ",
    "BBB     :                                      T  B##*##:#T#                    ",
    "                                     #                                          ",
    "BBB     .                                    *  BTT:###:#:##BT       BBBB       ",
    "                                   . #                                          ",
    "B                                                 .:#*###:#T#T *   TTBB##TB     ",
    "                                BB : #                                          ",
    "B #B                                         *  *  ####*##:######B    TTTTT#B   ",
    "                                B  * #                                          ",
    "  BT#                                      BT B   T  .*#*### ##B##B##BB     B   ",
    "                              B TT #.#                                          ",
    "  T# L                                      BT B    T  *#*#TBB  TBBT   T BTT#*TB",
    "  BBBB                         TB###:#                                          ",
    "    #R                                     T BT   RLB#  *#   TT.        .#*.T   ",
    "   *T *B                        #T #*                                           ",
    "    RL                                      #     #  RL #  T.    BT*B B    T    ",
    "       *L                        # B#                                           ",
    "   *T                                          BB#*L * .    :. :#:#BBT T        ",
    "        :                       BB  RL                                          ",
    " TTT###                                        ##*##   B   .. .:.#T     .   *   ",
    "        .                       BB#  #                                          ",
    " BB  ##L                                      #T##:##BB       ##.               ",
    " BB   ##                                     #B##*T T#T##B   # BTTBB BBT        ",
    " *                                                                              ",
    " BB    T#B   *                                #BBT.##:BBT###     BBTTT          ",
    "  T                           B      R                                          ",
    " BB       TTT                                #TTB.T#*##   T##   T   BB          ",
    "  BB                           #B    #                                          ",
    " BB                                            T#*..##     RL       T##    B    ",
    "   B                            T                                               ",
    " BB #                                        TT # .##  :   *         T##  T     ",
    "                                  BT                                            ",
    " BB *##B                                    BB # .#*  #                TB  T    ",
    "   *                               ##                                           ",
    " BB : BT#                                       BTT#B                    .  *   ",
    "                                    ##                                          ",
    " BB . T# L                                  B B##:*BBT                          ",
    "                                    R#                                          ",
    " BB     #R                                B#.####*..:#RL                     *  ",
    "                               #B   ##                                          ",
    " B  .   RL                               TTBB TT.    .*                         ",
    "                            B##*#BB###                                          ",
    " TT :  *T                              B#.*# TBB                                ",
    "                           #TB :B#                                              ",
    " #  *## *                              #B#*:  TBTTTTB                           ",
    "                          R #T .TT  TTT                                         ",
    " ####   #                              T##B     TB:*. BT                        ",
    "                          L#    BB  BBB                                         ",
    " TT # *T   *B                            TBB      T##  BT                       ",
    "                          RL   .BB  BBB                                         ",
    "    #       RL                            BB  B    TBB   B                      ",
    "                           T*  :    BBB                                         ",
    " B  ####B#  #R                           ####.  B     TBT B                     ",
    "                           *   *  B#BBB                                         ",
    " #      # B# L                            #:.  T B          B                   ",
    "                           #   # #TBBBB                                         ",
    "        # TB#                             RL       B                            ",
    "                            T* #R #TBBB                                         ",
    " #R #TBBB #T                               :          *                         ",
    "                       B*      #L#  BBB                                         ",
    " #L#  BBB   #                                                                   ",
    "                      RL       T     #                                          ",
    " #*#   #   B#                                                                   ",
    "                      L#    #  B                                                ",
    "BB#BB  #  BB#                                                                   ",
    "                      R #BR#T  #     #                                          ",
    "BB#B##TL  TT#                                       :                           ",
    "                       #BTR#  RB     #                                          ",
    "BB#BB  L  TT#                                                                   ",
    "                        T# L  BBL  TT#T                                         ",
    " B#BB B#  TT#                                                                   ",
    "                             BBB   TT#T                                         ",
    "TT#B  BL  TT#                                       *                           ",
    "                           #BBBBB  TT#T                                         ",
    "BB#TT     TT#                                                                   ",
    "                          #BBBBBT# TT#T                                         ",
    "   #  #L  TT#                     B                 T                           ",
    "                         B##* BB  BT##                                          ",
    "   #  ##  T#L                      TB               #        T             BBT  ",
    "                        #TB : BB  T# L                                          ",
    "   #   BL  #L                        #TBB  BTT   BBBTTT####BB T#BB TT  BBB## B  ",
    "                       R #T . BB    #R                                          ",
    "   #  #BB  R                          #B##BBBTBTTTTB#TT  BTT T#BB#TBBBBBBT#BT   ",
    "                       L#     BB    RL                                          ",
    "BB##B##BBB                            .###BBT  BBTT  . * BB TB ##T##T    TBT    ",
    "                       RL   .  B   *T                                           ",
    "#     BBBBB#                           TBTT  BTBBTT   TBB  ##T RL##T BT T##B *  ",
    "                        T*  : TT      T                                         ",
    "*     TBBBBB#                         TB   BT  BBBB###BB #TB######  ## ### #B # ",
    "                        * ##*  #      #                                         ",
    ": : BB#BB *##B                       T#  BT TT##B    TT## #######  ##.  ### #B #",
    " .                      #   ####B : BB#                                         ",
    ". . BB#BB : BT#                   * ## B#   TT###L T#B  ####LB## BB#L  RL ## #B ",
    "# # .               B*   T* # TTT . BB#                                         ",
    "    BB#BB . T# L                 R ## B  R  TT###L     ####T #R BB#L    R#### #B",
    " # R *             RL       #       BB#                                         ",
    "  .  B#BB     #R                 L R  L B#L TT##T    BTT#BT #  BB#L      R L####",
    "B # . .            L#  #B####  B  .  B#                                         ",
    "  : TT#B  .   RL                 L RR L BR  TT##BBBBBTTT BB#T BB##      # # LR##",
    "#B #   .           R #BB#      #  : TT#                                         ",
    "  #BBB#TT :  *T                  R # #R  L  TT#####B##T TB  BBB##  **  :   #  R#",
    "##B *               #BT##BBB      #BBB#                                         ",
    "#      #  *## *                     # R  L  TT#### T#B## T######  BBBBBBBBBB#T# ",
    "####                 T###      #      #                                         ",
    "#BB : B####   #               *      # L #L T#R###.  T#B#B TB TBBBBB#B#B#B#BBBTT",
    "  #BTB                  #BB : B####   #                                         ",
    "#BB . TTT # *T   *B             TB   RLL B#  #R ##    TBTB#B TB  B##TTTTTTTTT###",
    "B TT#B#TBB  :           #BB . TTT # *T                                          ",
    "#BB       #       RL              TT LL RBBB R L#L     TB TB#B TB#BTT T T TTBB T",
    "##T ###.  *             #BB       B   T                                         ",
    "#B  .  B  ####B#  #R               RRL   BBBB  LL   B   TB  TB##TT##T         TB",
    " #L# RL                 #B  .  B   TT####TT :  #      # B# L                ## T",
    "BBBBB#  #    TBB  T##BBBBTT#TTB        ## L  #  R            L#  #B####RL  BB # ",
    "#BBB#         # TB#                 RR# TBBBBBT#T#BB..BBBBBBBB#BB#TBBB#BT#T *  .",
    "## # R#  L           R #B #     T* T#T                                          ",
    " #   ###      # #T  B               ##   BTTB T BBBBBBBBBBBBBBBBT BT#T          ",
    "## T ### TB           #BT #          .                                          ",
    "     #BB . TTT       BT            ##   B B  T B B B B B B B     # RL TTTTTTT  #",
    "## T  ### T#B          T# #         : #                                         ",
    "     #BB              ##L        BB#. # # #TBBB  T T T T T T T   RL   TTTTTT  #T",
    "#  B B TB# T#T#B B    BB BB #BB     B                                           ",
    " #   #B  .  B          ##      BB#TTTTT T T  TTTBBBBBBBBBBBBB B   TB  TTTT  BT T",
    " BBBB#B  TTTBB     B  #T B# ###BBBBB# #                                         ",
    "TT . ##B##T#RL         R##  BBT#T    T TTTB#T TTT#TTT##.    #        *T    B    ",
    " BB#    BB    T BB##      *   .#  .:* B                                         ",
    "TT :#B #BB   T*BBBBB   ##TTT  ##       B# ##     #    #               B B##T B B",
    " .BB  B  TTT#BBBTB#* :::  :    #    .                                           ",
    "T##*               #BB###  BBB#   .   R#   T*         * B B .B   BB BB #BB  B B ",
    "BB     TTBB        #           . :  TT#                                         ",
    ":# # BBBBBBB   . * TTT #     B B# :    T##  TBTBB#     B B B BB  ## ## ### # # #",
    " ##.      ##. . *  BB#BBBB  B B# #  *                                           ",
    "** #BBBBBBBBBBB# #B BBBBBBBBBBBBBB# ::  TBTTBBTTT#BBB. # # # ###BB  B  BBB## # #",
    " ### BBB BBBBB# #B BBBBBBBBBBBBBB#  B###                                        ",
];
