//! The michael.slop skull, traced out of the mascot sprite.
//!
//! GENERATED by `gen_skull.py` from
//! `site/static/icons/skeleton.png`, region (9, 0) 23x19.
//!
//! The X region is app.js's, less one column of dark padding at the front
//! and two at the back -- a tighter silhouette, with no bone lost (measured:
//! the old trace had 3 bone-free columns left and 2 right). The
//! HEIGHT is two rows shorter on purpose: app.js takes 21 rows, of which
//! the last two are the neck stub below the teeth. Head alone is the
//! cleaner silhouette, and it stops the jump lifting a floating neck.
//!
//! Cells are LABELS, not pixels:
//!
//!   ` ` air   `#` bone   `*` `+` `.` outline, densest nearest the bone
//!
//! The outline is DERIVED, not traced. The sprite's own dark pixels are
//! baked in asymmetrically -- heavy under the bottom-right, thin across the
//! front -- which reads as a lopsided smudge once the skull turns. They are
//! discarded and the edge is regenerated from the bone shape, so it cannot
//! be heavier on one side: the rule does not know which side it is on.
//!
//! Outline cells must stay DARK at every angle and light level, or the
//! sockets fill in and the face stops reading as a face.

pub const COLS: usize = 29;
pub const ROWS: usize = 25;

/// One row per line. See the module header for the alphabet.
pub const SKULL: [&str; ROWS] = [
    "                             ",
    "                             ",
    "      ..................     ",
    "     ..++++++++++++++++..    ",
    "    ..++**************++..   ",
    "   ..++**############**++..  ",
    "   .++**##############**++.. ",
    "  ..+**################**++. ",
    "  .++*##################**+. ",
    "  .+**###################*+..",
    "  .+*####################*++.",
    "  .+*######****#####****#**+.",
    "  .+*#####**++**###**++**#*+.",
    "  .+*#####*++++*###*++++*#*+.",
    "  .+*#####**++**###**++**#*+.",
    "  .+*######****##*##****##*+.",
    "  .+*###########***#####***+.",
    "  .+**##################*+++.",
    "  .++****###############*+...",
    "  ..++++**##############*+.  ",
    "   ....++*###*##*##*##*#*+.  ",
    "      ..+*###*##*##*##*#*+.  ",
    "       .+****************+.  ",
    "       .++++++++++++++++++.  ",
    "       ....................  ",
];
