//! The michael.slop skull, traced out of the mascot sprite.
//!
//! GENERATED by `gen_skull.py` from
//! `site/static/icons/skeleton.png`, region (8, 0) 26x21 -- the same
//! crop `site/static/app.js:initSkullSpin` uses at runtime. Do not
//! re-derive the crop by eye: the site and panefx must show the same
//! face, and a second guess at the region is how the two drift apart.
//!
//! Cells are LABELS, not pixels:
//!
//!   ` ` air   `#` bone   `.` dark (outline, eye sockets, nose, tooth gaps)
//!
//! The dark cells must stay dark at every angle and every light level, or
//! the sockets fill in and the face stops reading as a face. That is a
//! property of the drawing, which is why the labels are stored rather than
//! a finished picture.

pub const COLS: usize = 26;
pub const ROWS: usize = 21;

/// One row per line. See the module header for the alphabet.
pub const SKULL: [&str; ROWS] = [
    "    ................      ",
    "   ..................     ",
    "  .....############...    ",
    "......##############...   ",
    ".....################...  ",
    "....##################... ",
    "....###################.. ",
    "...####################.. ",
    "...######....#####....#.. ",
    "...#####......###......#. ",
    "...#####......###......#. ",
    "...#####......###......#. ",
    "...######....##.##....##. ",
    "...###########...#####... ",
    "....##################..  ",
    ".......###############..  ",
    " .......##############..  ",
    "  ......###.##.##.##.#..  ",
    "      ..###.##.##.##.#..  ",
    "   ......##.##.##.##....  ",
    "   .....#####...........  ",
];
