//! The michael.slop skull, traced out of the mascot sprite.
//!
//! GENERATED by `gen_skull.py` from
//! `site/static/icons/skeleton.png`, region (8, 0) 26x19.
//!
//! The X region matches `site/static/app.js:initSkullSpin` exactly, so the
//! site and panefx show the same face -- do not re-derive it by eye. The
//! HEIGHT is two rows shorter on purpose: app.js takes 21 rows, of which
//! the last two are the neck stub below the teeth. Head alone is the
//! cleaner silhouette, and it stops the jump lifting a floating neck.
//!
//! Cells are LABELS, not pixels:
//!
//!   ` ` air   `#` bone   `.` dark (outline, eye sockets, nose, tooth gaps)
//!
//! The dark cells must stay dark at every angle and every light level, or
//! the sockets fill in and the face stops reading as a face. That is a
//! property of the drawing, which is why the labels are stored rather than
//! a finished picture.

pub const COLS: usize = 26;
pub const ROWS: usize = 19;

/// One row per line. See the module header for the alphabet.
pub const SKULL: [&str; ROWS] = [
    "    ................      ",
    "   ..................     ",
    "  .....############...    ",
    "......##############...   ",
    ".....################...  ",
    "....##################... ",
    "....###################.. ",
    "...####################.. ",
    "...######....#####....#.. ",
    "...#####......###......#. ",
    "...#####......###......#. ",
    "...#####......###......#. ",
    "...######....##.##....##. ",
    "...###########...#####... ",
    "....##################..  ",
    ".......###############..  ",
    " .......##############..  ",
    "  ......###.##.##.##.#..  ",
    "      ..###.##.##.##.#..  ",
];
