//! The warlock, traced out of the sprite.
//!
//! GENERATED by `gen_warlock.py` from
//! `Documents\(f)art\assets\darkfantasy\warlock.png`, figure region
//! (13, 8) 15x23, padded by 3 cells so the outline can close.
//!
//! A hooded skeleton facing RIGHT, in sunglasses, holding a wand. The
//! sprite's ten colours collapse to four parts, because a spinning ASCII
//! figure cannot carry ten and the attempt turns the silhouette to mush:
//! bone (the skull), shade (the sunglasses), robe (every blue plus the
//! black inside the hood), and wand.
//!
//! Edit `gen_warlock.py` and re-run it; do NOT hand-edit this file.

/// `#` bone · `=` sunglasses · `%` robe · `|` wand · `*+.` outline · ` ` air
pub const COLS: usize = 21;
pub const ROWS: usize = 29;

pub const WARLOCK: [&str; ROWS] = [
    "    ..............   ",
    "   ..++++++++++++..  ",
    "   .++**********++.  ",
    "   .+**%%%%%%%%**+.. ",
    "   .+*%%%%%%%%%%*++..",
    "   .+*%%%%%%%%%%**++.",
    "   .+*%%%%%######**+.",
    "   .+*%%%%%#======*+.",
    "  ..+*%%%%========*+.",
    "  .++*%%%%%#===#==*+.",
    "  .+**%%%%%######**+.",
    " ..+*%%%%%%%#####*++.",
    " .++*%%%%%%%#*#*#*+..",
    " .+**%%%%%%%******+. ",
    " .+*%%%%%%%%%*|||*+. ",
    " .+*%%%%%%%%%*|||*+. ",
    "..+*%%%%%%%%%%|||*+. ",
    ".++*%%%%%%#%%#|||*+. ",
    ".+**%%%%%%%#%|****+. ",
    ".+*%%%%%%%%||%%*+++. ",
    ".+*%%%%%%%||%%%*+... ",
    ".+*%%%%%%||%%%%*+.   ",
    ".+*%%%%%%%%%%%%*+.   ",
    ".+*%%%%%%%%%%%%*+.   ",
    ".+***%#%***%#%**+.   ",
    ".+++*%#*#**%#*#*+.   ",
    "...+************+.   ",
    "  .++++++++++++++.   ",
    "  ................   ",
];
